config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories

	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true



end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
	belongs_to :article 
	belongs_to :category


end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :article_categories
	has_many :articles, through: :article_categories

	validates :name, presence: true, 
					length: { minimum: 3, maximum: 25 }
	validates_uniqueness_of :name
					

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true,
						uniqueness: { case_sensitive: false },
						length: { minimum: 3, maximum: 15 }

	VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
						uniqueness: { case_sensitive: false },
						length: { maximum: 105 },
						format: { with: VALID_EMAIL_REGEX }

	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	@current_user  ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end 
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit

	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Your article was saved"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show

	end

	def destroy
		@article.destroy
		flash[:danger] = "Article deleted"
		redirect_to articles_path
	end

private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end

	def require_same_user
		if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You can only edit/delete your own article"
			redirect_to root_path
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_action :require_admin, except: [:index, :show]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category created"
			redirect_to categories_path
		else
			render 'new'
		end
	end

	def show
		
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger] = "Only admins can perform this action"
			redirect_to categories_path
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about
		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Successfully logged in"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Wrong email/password"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome #{@user.username}!"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @user.update(user_params)
			flash[:success] = "User successfully updated"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all user's articles have been deleted"
		redirect_to users_path
	end


	private

		def user_params
			params.require(:user).permit(:username, :email, :password)
		end

		def set_user
			@user = User.find(params[:id])
		end

		def require_same_user
			if current_user != @user and !current_user.admin?
				flash[:danger] = "You can only edit your own account"
				redirect_to root_path
			end
		end

		def require_admin
			if logged_in? and !current_user.admin?
				flash[:danger] = "Only admin users can perform that action"
				redirect_to root_path
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_article.html.erb
<div class="container-fluid">
	<% obj.each do |t| %>
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="well well-lg">
					<div class="article-title">
						<%= link_to(t.title, article_path(t)) %>
					</div>
					<div class="article-body">
						<%= truncate(t.description, length: 100) %>
						<div class="article-meta-details">
							<small>
								Created by: <%= t.user.username if t.user %>, <%= time_ago_in_words(t.created_at) %> ago, Last Updated: <%= time_ago_in_words(t.updated_at) %> ago
							</small>
						</div>
						
					</div>
					<% if logged_in? && (current_user == t.user || current_user.admin?) %>
						<div class="article-actions">
							<%= link_to("Edit Article", edit_article_path(t), class: "btn btn-xs btn-primary") %> 
							<%= link_to("Delete Article", article_path(t), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
	<% end %>	
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="container">
	<%= form_for(@article, :html => {class: "form"})  do |f| %>
	<div class="form-group">			
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article Content" %>
	</div>

	<%= f.submit class: 'btn btn-primary btn-lg' %>

	<% end %>

	<%= link_to "Cancel", articles_path, class: "btn btn-primary btn-lg", id: "bottom-button" %>
	
</div>

app/views/articles/edit.html.erb
<h1>Edit selected article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h2 align="center">Listing all articles</h2>

<div align="center">
	<%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
	<%= will_paginate %>
</div>

<div align="center">
	<%= link_to('Back to Homepage', root_path, class: "btn btn-default") %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create a new Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container-fluid">	
	<h2 align="center">Title: <%= @article.title %></h2>
	<div class="well col-xs-8 col-xs-offset-2">
		<% if @article.user %>
			<ul class="listing", align="center">
				<div class="row">
					<div class="col-md-4 col-md-offset-4">
						<li>Created by:</li>
						<li><%= link_to(gravatar_for(@article.user), user_path(@article.user)) if @article.user %></li>
						<li class="article-title"><%= link_to(@article.user.username, user_path(@article.user)) %></li>
						<li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
					</div>
				</div>
			</ul>
		<% end %>
		<h4 class="center description"><strong>Description: </strong></h4>
		<div class="article-body">
			<%= @article.description %>
		</div>
		<div class="article-actions">
			<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
				<%= link_to("Edit Article", edit_article_path(@article), class: "btn btn-xs btn-primary") %> 
				<%= link_to("Delete Article", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
			<% end %>
			<%= link_to("Back to Articles", articles_path, class: "btn btn-xs btn-success") %>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<h2 align="center">Categories</h2>
<div class="container-fluid" align="center">
	<%= will_paginate %>
	<% @categories.each do |t| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li class="article-title">
						<%= link_to("#{t.name}", category_path(t)) %>
					</li>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h2 align="center">Create New Category</h2>
<%= render 'shared/errors', obj: @category %>

<div class="container-fluid">
	<%= form_for(@category, :html => {class: "form"})  do |f| %>
		<div class="form-group">			
			<%= f.label :name %>
			<%= f.text_field :name, class: "form-control", placeholder: "Name of category", autofocus: true %>
		</div>
		<%= f.submit class: 'btn btn-primary btn-lg' %>
	<% end %>
	<%= link_to "Cancel", articles_path, class: "btn btn-primary btn-lg", id: "bottom-button" %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; Brian Arpaio | arpaio@gmail.com
		</small>
		<nav>
			<ul>
				<li><%= link_to("About", about_path) %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">	
	<% flash.each do |name, msg| %>
		<div class='alert alert-<%= "#{name}" %> alert-dismissible', role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<ul>
				<li><%= msg %></li>
			</ul>
		</div>
	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("AlphaBlog", root_path, class: "navbar-brand", id: "logo") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="nav-links collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to("Blog", articles_path) %><span class="sr-only">(current)</span></li>
        <li><%= link_to("Users", users_path) %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Options <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to("Create New Article", new_article_path) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to("View Users", users_path) %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to("All Categories", categories_path) %></li>
            <li role="separator" class="divider"></li>
            <% Category.all.each do |cat| %>
              <li><%= link_to("#{cat.name}", category_path(cat)) %></li>
            <% end %>
            <% if logged_in? and current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to("New Category", new_category_path) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search(not working yet)">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to("Logout", logout_path, method: :delete) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your <%= "Admin" if current_user.admin? %> Profile<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to("Edit Your Profile", edit_user_path(current_user)) %></li>
              <li><%= link_to("View Your Profile", user_path(current_user)) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to("Logout", logout_path, method: :delete) %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to("Create Account", signup_path) %></li>
          <li><%= link_to("Log In", login_path) %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<div class="container">
	<%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages About Page</h1>

<h2>About</h2>
<p>This is the About Page for the PagesController</p>
<%= link_to('Home', root_path) %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to AlphaBlog!</h1>
  <p><%= link_to("Sign Up Now", signup_path, class: "btn btn-primary btn-lg btn-xlarge") %></p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h2 class="panel-title">The following errors occured:</h2>
		</div>
		<div class="panel-body">
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="container">
	<%= form_for(@user, :html => {class: "form"})  do |f| %>
	<div class="form-group">			
		<%= f.label :username %>
		<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
	</div>
	<div class="form-group">			
		<%= f.label :email %>
		<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
	</div>
	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control", placeholder: "Enter Password" %>
	</div>

	<%= f.submit(@user.new_record? ? "Submit" : "Update Account", class: 'btn btn-primary btn-lg') %>
	<% end %>
	<%= link_to "Cancel", articles_path, class: "btn btn-primary btn-lg", id: "bottom-button" %>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">AlphaBlog Users</h1>
<div class="container-fluid", align="center">
	<%= will_paginate %>
	<% @users.each do |t| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li><%= link_to(gravatar_for(t), user_path(t)) %></li>
					<li class="article-title"><%= link_to(t.username, user_path(t)) %></li>
					<li><small><%= pluralize(t.articles.count, "article") if t.articles %></small></li>
					<% if logged_in? and current_user.admin? %>
						<li><%= link_to("Delete User", user_path(t), method: :delete, data: { confirm: "Are you sure you want to delete the user and all of their articles?"}) %></li>
					<% end %>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Signup for AlphaBlog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="container-fluid">
	<h1 align="center">Welcome to <%= @user.username %>'s Profile</h1>
	<div class="row">
		<div class="col-md-4 col-md-offset-4 center">
			<%= gravatar_for(@user, size: 150) %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4 col-md-offset-4 center">
			<h4><%= @user.email %></h4>
		</div>
	</div>
	<div class="row">
		<h3 align="center"><%= @user.username %>'s Articles:</h3>
	</div>
	<div align="center">
		<%= will_paginate @user_articles %>
	</div>
	<%= render 'articles/article', obj: @user_articles %>
	<div align="center">
		<%= will_paginate @user_articles %>
	</div>
</div>